### ISSUE TITLE
/data/uncompound_lexicon.txt is missing

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/PyTib#6]
* Current master
* 3.6
* Mac os X

### Description

Right out of the installation from master on git.

FileNotFoundError: [Errno 2] No such file or directory: '/Users/mikko/dev/py3/lib/python3.6/site-packages/pytib/data/uncompound_lexicon.txt'

### What I Did

```
import pytib
```

**Comment by drupchen** [comment]
The file is not missing: https://github.com/Esukhia/PyTib/tree/master/pytib/data

Please look [here](https://github.com/Esukhia/PyTib/blob/master/tests/seg_test.py) for a test of how it is meant to be used. 

You seem to be struggling with paths, which you can configure [in this file](https://github.com/Esukhia/PyTib/blob/master/pytib/__init__.py#L12)

**Comment by mikkokotila** [comment]
Thanks yes, I figured it's something with paths and manual copied it. But just to let you know that following the install instructions, this is the case.

**Comment by drupchen** [comment]
yes. since the project is not at a point where it can be made into a real package, I don't expect users to install it in site-packages, so I don't consider this a bug for now.
